In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

In [2]:
#pkg = mp.jupyter.open_package()
#pkg = mp.jupyter.open_source_package()
#pkg

pkg = mp.open_package('http://library.metatab.org/federalreserve.gov-consumer_finances-2016e2019-inherit-1.2.1.csv')

# Create Dataframes
df = pkg.resource('inherit_scf_16_19').dataframe()

df.head()

,year,case_id,record_id,implicate_id,age_1,age_2,hisp,race,addtional_race,unusual_income,...,n_transfer,any_transfer,any_inherit,hhsize,networthpc,assetpc,gi_pv_10,gi_pv_7,gi_pv_5,gi_value_cd
0,2016,1,11,1,71,0,5,white,5,3,...,0,0,0,1,187954.520394,188358.677918,0.0,0.0,0.0,0.0
1,2016,1,12,2,71,0,5,white,5,3,...,0,0,0,1,188071.513361,188465.035162,0.0,0.0,0.0,0.0
2,2016,1,13,3,71,0,5,white,5,3,...,0,0,0,1,187965.156118,188358.677918,0.0,0.0,0.0,0.0
3,2016,1,14,4,71,0,5,white,5,3,...,0,0,0,1,187965.156118,188358.677918,0.0,0.0,0.0,0.0
4,2016,1,15,5,71,0,5,white,5,3,...,0,0,0,1,188071.513361,188465.035162,0.0,0.0,0.0,0.0